
MONGO_General:
  url: 'localhost'
  port: 27017
  user:
  password:

Redis_General:
  uri: 'localhost'
  port: 6380
  password:

logLevel:

JWT_Config:
  Key_Path: '/home/iambigj/me/projects/telegram-bot/JWT_Key'