
MONGO_General:
  url: 'localhost'
  port: 27017
  user:
  password:

Redis_General:
  uri: 'localhost'
  port: 6380
  password:

logLevel:


email:
  service: "GMAIL"
  host: "smtp.gmail.com"
  port: 465
  secure: true
  user: 'alijavadij@gmail.com'
  pass: 'aLi@1263*J<ij'

JWT_Config:
  Key_Path: '/home/iambigj/me/projects/telegram-bot/JWT_Key'