
MONGO_General:
  url: 'localhost'
  port: 27017
  user:
  password:

Redis_General:
  uri: 'localhost'
  port: 6380
  password:

logLevel:


Mailer:
  host: "127.0.0.1"
  port: 25
  secure: false
  username: 'alijavadij@gmail.com'
  password: 'aLi@1263*J<ij'

JWT_Config:
  Key_Path: '/home/iambigj/me/projects/telegram-bot/JWT_Key'