version: '3.8'

services:
  # nodeApp:
  #   build: .
  #   ports:
  #     - "3003:3003"
  #   depends_on:
  #     redis:
  #       condition: service_healthy
  #     mongo:
  #       condition: service_healthy
  #   networks:
  #     - app-network


  redis:
    image: redis:latest
    container_name: redis
    command: ["redis-server", "--appendonly", "yes"]  # enable AOF persistence
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data    # persist Redis data across restarts
    networks:
      - app-network
    healthcheck:  # Added healthcheck for redis
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3


  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    networks:
      - app-network
    healthcheck: # Added healthcheck for mongo
      test: [ "CMD", "mongo", "--eval", "db.adminCommand('ping')" ]
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
      - mongo_data:/data/db

networks:
  app-network:
    driver: bridge

volumes:
  redis_data:
  mongo_data: