version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6380:6379"

    networks:
      - app-network

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"

    networks:
      - app-network

networks:
  app-network:
    driver: bridge
